spring:
  application:
    name: store
    cart:
      maxLimit: 10
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
  jwt:
    secret: qSfeX1VAzAaWCy8tHgK5cPiND7UL8PCSZBRFoT/iZnVu2gYSUtL62kReMMPzU+8y0MjVznRmE+GlEUeE9Vww+w==
    accessTokenExpiration: 300  #  3m
    refreshTokenExpiration: 604800  # 7d